// Code generated by "stringer -type=Action -linecomment"; DO NOT EDIT.

package sockets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdjustScore-0]
	_ = x[CalculateScore-1]
	_ = x[ChangeCompetitor-2]
	_ = x[ChangeEvent-3]
	_ = x[FinalizeScore-4]
	_ = x[RegisterDisplay-5]
	_ = x[RegisterJudge-6]
	_ = x[StartTimer-7]
	_ = x[StopTimer-8]
	_ = x[SubmitDeductions-9]
	_ = x[SubmitNandu-10]
	_ = x[SubmitScore-11]
	_ = x[ClientInit-12]
	_ = x[ListCompetitors-13]
	_ = x[ListEvents-14]
	_ = x[NotifyCompetitor-15]
	_ = x[NotifyEvent-16]
	_ = x[NotifyFinalScore-17]
	_ = x[Rescore-18]
	_ = x[RingStatus-19]
	_ = x[RingUpdate-20]
	_ = x[Score-21]
	_ = x[StartEvent-22]
	_ = x[StopEvent-23]
	_ = x[LastDisplay-24]
	_ = x[LiveDisplay-25]
	_ = x[InvalidAction-26]
}

const _Action_name = "adjust-scorecalculate-scorechange-competitorchange-eventfinalize-scoreregister-displayregister-judgestart-timerstop-timersubmit-deductionssubmit-nandusubmit-scoreinitlist-competitorslist-eventsnotify-competitornotify-eventnotify-final-scorerescorering-statusring-updatescorestart-eventstop-eventlast-displaylive-displayinvalid"

var _Action_index = [...]uint16{0, 12, 27, 44, 56, 70, 86, 100, 111, 121, 138, 150, 162, 166, 182, 193, 210, 222, 240, 247, 258, 269, 274, 285, 295, 307, 319, 326}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
