competition:
    name: 2024 University Wushu Games
    theme: '/static/theme-red.css'

server:
    port: 8000
    home: './app'
    static: './app/static'

judge:
    login: false

logging:
    access: ""
    api: ""
    sockets: ""
        
database:
    enabled: true
    host: localhost:5432
    user: tpzadmin
    password: tpzadmin
    dbname: tpz
